name: Roxy Migurdia

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --exclude=my_env --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --exclude=my_env --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Python script
      run: |
        python KN_41_VaYu-2/script.py  # Вказуємо шлях до скрипта

    - name: Test with pytest
      run: |
        pytest KN_41_VaYu-2/test_requests.py  # Вказуємо шлях до конкретного тесту
